/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSetupStatus"];
        put?: never;
        /** @description 首用户仍须持久化成功后发布认证，不使用普通配置的应用优先语义。 */
        post: operations["initializeWebUi"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConfigState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSystemConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/modules/{module}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConfigModule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 无应用/写文件副作用；候选基于活动源，整张引用图一次校验。 */
        post: operations["validateCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/modules/{module}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 普通模块表单入口；候选只能包含一项且 module 必须与 URL 一致，拒绝其他模块混入。 */
        post: operations["validateModuleCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/modules/{module}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 普通模块表单入口；与组合采用共用应用编排，但只接收一个同模块 change。 */
        post: operations["applyModuleCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description operation_id 首次发送前固定；同 ID 不同命令摘要拒绝。非终态返回 202。 已应用但文件未同步也是明确结果，不回滚为旧态，不把重试文件同步变成重新应用。 并发文件变化返回冲突；未知结果先查 operation 和活动资源，不自动重放。 */
        post: operations["applyCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConfigOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/files/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 无效外部 YAML 不返回正文；只读/敏感变化仅返回受保护分类。采用使用 Candidate。 */
        get: operations["getExternalDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/files/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 以活动源还原受管文件，不重载 DNS；必须显式确认覆盖所见差异。 */
        post: operations["restoreConfigFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/files/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 只同步当前已应用源，不重新 prepare 或重放创建/改名。 */
        post: operations["retryConfigPersistence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 只读查询使用 JSON body，共用 HTTP/WS filter，避免把身份过滤写入 URL。 filter 在分页前应用；时间为 UTC 毫秒半开区间；cursor 与 filter、方向、水位绑定。 无固定 31 天限制，但最大跨度为 3650 天；无 COUNT、页码直跳或伪造总数。 */
        post: operations["searchQueries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getQueryDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRetentionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retention/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 后端采样详情 DB 加 WAL 长度；S 大于 T 用 R 天，否则 R+G；保存不立即清理。 */
        post: operations["previewRetention"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getServiceMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProcessMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 同源 Cookie 鉴权和 Origin 校验；upgrade 后独立连接 owner，不受普通 HTTP 15s deadline 截断。 不在 URL 携带 token。登出/过期回收；慢消费者关闭并 resync。JSON 帧使用共享 schema。 */
        get: operations["subscribeEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 内部 v2 文件契约，不作为 HTTP 读写 payload；当前生产 loader 尚未接线 */
        Configuration: {
            /** @constant */
            version: 2;
            work: {
                path: components["schemas"]["Path"];
                rules_path: components["schemas"]["Path"];
            };
            database: {
                /** @constant */
                type: "sqlite";
                path: components["schemas"]["Path"];
                records_path: components["schemas"]["Path"];
            };
            logs: components["schemas"]["Logs"];
            webui: {
                enable: boolean;
                address: string;
                port: number;
                /** Format: uri */
                public_origin?: string;
                users?: {
                    name: components["schemas"]["Name"];
                    password_hash: string;
                }[];
            };
            dns: components["schemas"]["Dns"];
            statistics?: components["schemas"]["Statistics"];
            listener?: components["schemas"]["Listener"][];
            upstreams?: components["schemas"]["Upstream"][];
            strategy?: components["schemas"]["Strategy"][];
            hosts?: components["schemas"]["Hosts"][];
            outbound?: components["schemas"]["Outbound"][];
            rule_set?: components["schemas"]["RuleSet"][];
            clients?: components["schemas"]["Client"][];
        };
        ConfigChange: {
            /** @constant */
            module: "listener";
            change: components["schemas"]["ListenerMutation"];
        } | {
            /** @constant */
            module: "upstreams";
            change: components["schemas"]["UpstreamMutation"];
        } | {
            /** @constant */
            module: "strategy";
            change: components["schemas"]["StrategyMutation"];
        } | {
            /** @constant */
            module: "hosts";
            change: components["schemas"]["HostsMutation"];
        } | {
            /** @constant */
            module: "outbound";
            change: components["schemas"]["OutboundMutation"];
        } | {
            /** @constant */
            module: "rule_set";
            change: components["schemas"]["RuleSetMutation"];
        } | {
            /** @constant */
            module: "clients";
            change: components["schemas"]["ClientMutation"];
        } | {
            /** @constant */
            module: "dns";
            change: components["schemas"]["Dns"];
        } | {
            /** @constant */
            module: "statistics";
            change: components["schemas"]["Statistics"];
        } | {
            /** @constant */
            module: "logs";
            change: components["schemas"]["Logs"];
        };
        ListenerMutation: {
            /** @constant */
            action: "create";
            value: components["schemas"]["Listener"];
        } | {
            /** @constant */
            action: "update";
            original_name: components["schemas"]["Name"];
            value: components["schemas"]["Listener"];
        };
        UpstreamMutation: {
            /** @constant */
            action: "create";
            value: components["schemas"]["Upstream"];
        } | {
            /** @constant */
            action: "update";
            original_name: components["schemas"]["Name"];
            value: components["schemas"]["Upstream"];
        };
        StrategyMutation: {
            /** @constant */
            action: "create";
            value: components["schemas"]["Strategy"];
        } | {
            /** @constant */
            action: "update";
            original_name: components["schemas"]["Name"];
            value: components["schemas"]["Strategy"];
        };
        HostsMutation: {
            /** @constant */
            action: "create";
            value: components["schemas"]["Hosts"];
        } | {
            /** @constant */
            action: "update";
            original_name: components["schemas"]["Name"];
            value: components["schemas"]["Hosts"];
        };
        OutboundMutation: {
            /** @constant */
            action: "create";
            value: components["schemas"]["Outbound"];
        } | {
            /** @constant */
            action: "update";
            original_name: components["schemas"]["Name"];
            value: components["schemas"]["Outbound"];
        };
        RuleSetMutation: {
            /** @constant */
            action: "create";
            value: components["schemas"]["RuleSet"];
        } | {
            /** @constant */
            action: "update";
            original_name: components["schemas"]["Name"];
            value: components["schemas"]["RuleSet"];
        };
        ClientMutation: {
            /** @constant */
            action: "create";
            value: components["schemas"]["Client"];
        } | {
            /** @constant */
            action: "update";
            original_name: components["schemas"]["Name"];
            value: components["schemas"]["ClientEdit"];
        };
        ModuleSource: {
            /** @constant */
            module: "listener";
            value: components["schemas"]["Listener"];
        } | {
            /** @constant */
            module: "upstreams";
            value: components["schemas"]["Upstream"];
        } | {
            /** @constant */
            module: "strategy";
            value: components["schemas"]["Strategy"];
        } | {
            /** @constant */
            module: "hosts";
            value: components["schemas"]["Hosts"];
        } | {
            /** @constant */
            module: "outbound";
            value: components["schemas"]["Outbound"];
        } | {
            /** @constant */
            module: "rule_set";
            value: components["schemas"]["RuleSet"];
        } | {
            /** @constant */
            module: "clients";
            value: components["schemas"]["Client"];
        } | {
            /** @constant */
            module: "dns";
            value: components["schemas"]["Dns"];
        } | {
            /** @constant */
            module: "statistics";
            value: components["schemas"]["Statistics"];
        } | {
            /** @constant */
            module: "logs";
            value: components["schemas"]["Logs"];
        };
        Name: string;
        ClientId: string;
        Revision: string;
        OperationId: components["schemas"]["Revision"];
        RecordId: components["schemas"]["Revision"];
        Cursor: string;
        /** @description 十进制 u64，不超过 18446744073709551615，不能先转 Number */
        DecimalU64: string;
        SafeInteger: number;
        Bytes: number;
        /** @description 沿用紧凑 duration parser，整数/小数加 ns/us/ms/s/m/h/d/w，可组合；范围由字段语义约束 */
        Duration: string;
        Path: string;
        /** @description 另按 UTF-8 字节限制为 256 KiB */
        InlineText: string;
        /** @enum {string} */
        ConfigModule: "listener" | "upstreams" | "strategy" | "hosts" | "outbound" | "rule_set" | "clients" | "dns" | "statistics" | "logs";
        Credentials: {
            username: string;
            /** @description 不 trim；后端按 UTF-8 bytes 校验，setup 为 12..1024，login 为 1..1024 */
            password: string;
        };
        SetupStatus: {
            /** @enum {string} */
            state: "required" | "ready";
        };
        Session: {
            user: {
                name: components["schemas"]["Name"];
            };
            /** Format: date-time */
            expires_at: string;
        };
        SecretRef: {
            env: string;
        } | {
            file: components["schemas"]["Path"];
        };
        Optimistic: {
            enabled: boolean;
            answer_ttl: components["schemas"]["Duration"];
            max_age: components["schemas"]["Duration"];
        };
        CacheOverride: {
            enabled: boolean;
            optimistic?: components["schemas"]["Optimistic"];
        };
        TtlOverride: {
            enabled?: boolean;
            min?: components["schemas"]["Duration"];
            max?: components["schemas"]["Duration"];
        };
        /** @description custom 必须有 custom_ip，其余模式禁止；IP/CIDR 语义由公共 validator 检查 */
        Ecs: {
            /** @enum {string} */
            mode: "disabled" | "client" | "custom";
            custom_ip?: string;
        };
        Snapshot: {
            /** @default false */
            enabled: boolean;
            /** @default ./data/dns-cache.db */
            path: components["schemas"]["Path"];
            /**
             * @description 1s 至 1d
             * @default 5m
             */
            snapshot_interval: components["schemas"]["Duration"];
        };
        GlobalCache: {
            enabled: boolean;
            memory: {
                max_size_bytes: components["schemas"]["Bytes"];
            };
            /** @description 1s 至 5m */
            failure_ttl: components["schemas"]["Duration"];
            optimistic: components["schemas"]["Optimistic"];
            persistence?: components["schemas"]["Snapshot"];
        };
        Dns: {
            cache?: components["schemas"]["GlobalCache"];
            ttl_override?: components["schemas"]["TtlOverride"];
            edns_client_subnet?: components["schemas"]["Ecs"];
            resolve_log?: {
                enable: boolean;
            };
        };
        Retention: {
            /** @default 7 */
            days: number;
            /**
             * @description days 加 grace_days 不超过 3650
             * @default 3
             */
            grace_days: number;
            /** @default 1073741824 */
            reference_size_bytes: components["schemas"]["Bytes"];
        };
        Statistics: {
            retention?: components["schemas"]["Retention"];
        };
        Logs: {
            enable: boolean;
            /** @enum {string} */
            level: "trace" | "debug" | "info" | "warn" | "error";
            path: components["schemas"]["Path"];
        };
        ClientMatch: {
            ips?: string[];
        };
        Client: {
            name: components["schemas"]["Name"];
            client_id: components["schemas"]["ClientId"];
            match?: components["schemas"]["ClientMatch"];
            strategy?: components["schemas"]["Name"];
            cache?: components["schemas"]["CacheOverride"];
            ttl_override?: components["schemas"]["TtlOverride"];
            edns_client_subnet?: components["schemas"]["Ecs"];
        };
        ClientEdit: {
            name: components["schemas"]["Name"];
            match?: components["schemas"]["ClientMatch"];
            strategy?: components["schemas"]["Name"];
            cache?: components["schemas"]["CacheOverride"];
            ttl_override?: components["schemas"]["TtlOverride"];
            edns_client_subnet?: components["schemas"]["Ecs"];
        };
        Listener: components["schemas"]["UdpListener"] | components["schemas"]["TcpListener"] | components["schemas"]["DohListener"];
        UdpListener: {
            name: components["schemas"]["Name"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "UdpListener";
            addresses: string[];
            port: number;
            strategy: components["schemas"]["Name"];
            hosts?: components["schemas"]["Name"];
        };
        TcpListener: {
            name: components["schemas"]["Name"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "TcpListener";
            addresses: string[];
            port: number;
            strategy: components["schemas"]["Name"];
            hosts?: components["schemas"]["Name"];
        };
        DohListener: {
            name: components["schemas"]["Name"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DohListener";
            routes: {
                path: string;
                strategy: components["schemas"]["Name"];
            }[];
            endpoints: components["schemas"]["DohEndpoint"][];
        };
        DohEndpoint: {
            name: components["schemas"]["Name"];
            addresses: string[];
            port: number;
            /** @description terminate 要求两个文件；external 禁止文件残留 */
            tls: {
                /** @enum {string} */
                mode: "terminate" | "external";
                certificate_file?: components["schemas"]["Path"];
                private_key_file?: components["schemas"]["Path"];
            };
            client_ip: {
                /** @enum {string} */
                source: "peer" | "forwarded_header" | "proxy_protocol";
                /** @enum {string} */
                header?: "X-Forwarded-For" | "X-Real-IP" | "Forwarded";
                trusted_proxies?: string[];
                /** @enum {string} */
                on_missing?: "reject" | "use_peer";
                /** @enum {string} */
                on_invalid?: "reject" | "use_peer";
            };
        };
        Upstream: components["schemas"]["HostsUpstream"] | components["schemas"]["DohUpstream"] | components["schemas"]["UpstreamGroup"];
        HostsUpstream: {
            name: components["schemas"]["Name"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "HostsUpstream";
            /** @enum {string} */
            format: "json" | "hosts";
            hosts: components["schemas"]["InlineText"];
        };
        DohUpstream: {
            name: components["schemas"]["Name"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DohUpstream";
            /** Format: uri */
            address: string;
            bootstrap?: components["schemas"]["Name"];
            connect_ip?: string;
            proxy?: components["schemas"]["Name"];
            edns_client_subnet?: components["schemas"]["Ecs"];
        };
        UpstreamMember: {
            name: components["schemas"]["Name"];
            /** @default 1 */
            weight: number;
        };
        /** @enum {string} */
        UpstreamMode: "parallel" | "round-robin" | "load-balance" | "failover";
        UpstreamGroup: {
            name: components["schemas"]["Name"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "UpstreamGroup";
            upstreams: components["schemas"]["UpstreamMember"][];
            upstream_mode: components["schemas"]["UpstreamMode"];
            timeout: components["schemas"]["Duration"];
            fallbacks?: components["schemas"]["UpstreamMember"][];
            fallback_upstream_mode?: components["schemas"]["UpstreamMode"];
            fallback_timeout?: components["schemas"]["Duration"];
        };
        Strategy: {
            name: components["schemas"]["Name"];
            default_upstream: components["schemas"]["Name"];
            rules: components["schemas"]["StrategyRule"][];
            cache?: components["schemas"]["CacheOverride"];
            ttl_override?: components["schemas"]["TtlOverride"];
            edns_client_subnet?: components["schemas"]["Ecs"];
        };
        /** @description rule_set 与 hosts 恰有一项；rule_set 必须有 upstream，hosts 禁止 upstream */
        StrategyRule: {
            rule_set?: string;
            hosts?: components["schemas"]["Name"];
            upstream?: components["schemas"]["Name"];
            edns_client_subnet?: components["schemas"]["Ecs"];
        };
        Hosts: {
            name: components["schemas"]["Name"];
            /** @constant */
            type: "const";
            /** @enum {string} */
            format: "json" | "hosts";
            hosts: components["schemas"]["InlineText"];
        } | {
            name: components["schemas"]["Name"];
            /** @constant */
            type: "file";
            /** @enum {string} */
            format: "json" | "hosts";
            path: components["schemas"]["Path"];
            /** @default false */
            auto_update: boolean;
            update_interval?: components["schemas"]["Duration"];
        };
        Outbound: {
            name: components["schemas"]["Name"];
            /** @constant */
            type: "socks5";
            proxy_url: components["schemas"]["SecretRef"];
        };
        RuleSet: {
            name: components["schemas"]["Name"];
            /** @constant */
            type: "const";
            /** @enum {string} */
            format: "json" | "clash" | "dat";
            rule: components["schemas"]["InlineText"];
        } | {
            name: components["schemas"]["Name"];
            /** @constant */
            type: "file";
            /** @enum {string} */
            format: "json" | "clash" | "dat";
            path: components["schemas"]["Path"];
            /** @default false */
            auto_update: boolean;
            update_interval?: components["schemas"]["Duration"];
        } | {
            name: components["schemas"]["Name"];
            /** @constant */
            type: "remote";
            /** @enum {string} */
            format: "json" | "clash" | "dat";
            /** Format: uri */
            url: string;
            proxy?: components["schemas"]["Name"];
            /** @default false */
            auto_update: boolean;
            update_interval?: components["schemas"]["Duration"];
        };
        Preconditions: {
            active_revision: components["schemas"]["Revision"];
            observed_file_revision: components["schemas"]["Revision"];
        };
        ConfigState: {
            active_revision: components["schemas"]["Revision"];
            runtime_revision: components["schemas"]["Revision"];
            persisted_revision: components["schemas"]["Revision"] | null;
            observed_file_revision: components["schemas"]["Revision"];
            files: {
                source: components["schemas"]["FileCondition"];
                derived: components["schemas"]["FileCondition"] | null;
            };
            /** @enum {string} */
            synchronization: "synced" | "applying" | "persisting" | "applied_unpersisted" | "blocked";
            operation_id: components["schemas"]["OperationId"] | null;
        };
        /** @enum {string} */
        FileCondition: "unchanged" | "changed" | "missing" | "unreadable" | "oversized";
        Candidate: {
            expected: components["schemas"]["Preconditions"];
            changes: components["schemas"]["ConfigChange"][];
            discard_external_changes: boolean;
        };
        ApplyRequest: {
            operation_id: components["schemas"]["OperationId"];
            candidate: components["schemas"]["Candidate"];
            validation_token: components["schemas"]["Revision"];
            confirmations: components["schemas"]["ImpactKind"][];
        };
        /** @enum {string} */
        ImpactKind: "rename_references" | "listener_rebind" | "retention_shortening" | "discard_external_changes";
        ValidationResult: {
            validation_token: components["schemas"]["Revision"];
            expected: components["schemas"]["Preconditions"];
            expires_at_ms: components["schemas"]["SafeInteger"];
            required_confirmations: components["schemas"]["ImpactKind"][];
            affected_names: components["schemas"]["Name"][];
        };
        FileSyncRequest: {
            operation_id: components["schemas"]["OperationId"];
            expected: components["schemas"]["Preconditions"];
            discard_external_changes: boolean;
        };
        /** @enum {string} */
        ErrorCode: "INVALID_ARGUMENT" | "VALIDATION_FAILED" | "PAYLOAD_TOO_LARGE" | "VERSION_UNSUPPORTED" | "AUTH_REQUIRED" | "FORBIDDEN" | "NOT_FOUND" | "ACTIVE_REVISION_CONFLICT" | "FILE_REVISION_CONFLICT" | "EXTERNAL_CHANGES_REQUIRE_CONFIRMATION" | "OPERATION_ID_REUSED" | "OPERATION_BUSY" | "VALIDATION_EXPIRED" | "PERSISTENCE_FAILED" | "APPLY_FAILED" | "COMPENSATION_FAILED" | "CURSOR_EXPIRED" | "RATE_LIMITED" | "SERVICE_UNAVAILABLE";
        ErrorEnvelope: {
            code: components["schemas"]["ErrorCode"];
            request_id: string;
            message: string;
            retryable: boolean;
            field_errors: {
                path: string;
                code: components["schemas"]["ErrorCode"];
            }[];
        };
        OperationResult: {
            operation_id: components["schemas"]["OperationId"];
            status: components["schemas"]["OperationStatus"];
        };
        OperationStatus: {
            /** @enum {string} */
            state: "preparing" | "applying" | "unknown";
        } | {
            /** @constant */
            state: "persisting";
            active_revision: components["schemas"]["Revision"];
        } | {
            /** @constant */
            state: "applied_synced";
            active_revision: components["schemas"]["Revision"];
            persisted_revision: components["schemas"]["Revision"];
        } | {
            /** @constant */
            state: "applied_unpersisted";
            active_revision: components["schemas"]["Revision"];
            persisted_revision: components["schemas"]["Revision"] | null;
            error: components["schemas"]["ErrorCode"];
        } | {
            /** @constant */
            state: "rejected";
            error: components["schemas"]["ErrorCode"];
        } | {
            /** @constant */
            state: "compensation_failed";
            active_revision: components["schemas"]["Revision"] | null;
            error: components["schemas"]["ErrorCode"];
        };
        ConfigRead: {
            state: components["schemas"]["ConfigState"];
            values: components["schemas"]["ModuleSource"][];
            effective: {
                path: string;
                /** @enum {string} */
                source: "default" | "global" | "strategy" | "client" | "explicit";
                value: string | boolean | components["schemas"]["SafeInteger"];
            }[];
            references: {
                from_module: components["schemas"]["ConfigModule"];
                from_name: components["schemas"]["Name"];
                path: string;
                to_name: components["schemas"]["Name"];
            }[];
            runtime: components["schemas"]["ModuleRuntime"][];
        };
        ModuleRuntime: {
            /** @constant */
            module: "listener";
            name: components["schemas"]["Name"];
            bindings: {
                endpoint_name: components["schemas"]["Name"] | null;
                address: string;
                port: number;
                transport: components["schemas"]["Transport"];
                accepting: boolean;
            }[];
        } | {
            /** @enum {string} */
            module: "hosts" | "rule_set";
            name: components["schemas"]["Name"];
            /** @enum {string} */
            condition: "ready" | "stale" | "failed" | "unavailable";
            last_updated_at_ms: components["schemas"]["SafeInteger"] | null;
            next_update_at_ms: components["schemas"]["SafeInteger"] | null;
            error: components["schemas"]["ErrorCode"] | null;
        } | {
            /** @constant */
            module: "dns";
            snapshot: components["schemas"]["CacheSnapshotStatus"];
        };
        CacheSnapshotStatus: {
            /** @enum {string} */
            state: "disabled" | "idle" | "writing" | "restoring" | "failed";
            owner_revision: components["schemas"]["Revision"];
            generation: components["schemas"]["DecimalU64"];
            file_bytes: components["schemas"]["DecimalU64"] | null;
            last_success_at_ms: components["schemas"]["SafeInteger"] | null;
            last_error: components["schemas"]["ErrorCode"] | null;
        };
        /** @description 最多 128 项且完整 JSON 不超过 2 MiB，超限返回 PAYLOAD_TOO_LARGE，不截断。 按同命名空间 name 配对，不猜测改名；只有 active 的条目不授权删除。 普通资源 URL 的 query 按源配置保留，不伪造替代 URL；管理认证 token 不进入配置差异或 URL。 */
        ExternalDiff: {
            expected: components["schemas"]["Preconditions"];
            editable: {
                active: components["schemas"]["ModuleSource"] | null;
                external: components["schemas"]["ModuleSource"] | null;
            }[];
            protected_changes: ("work" | "database" | "webui" | "protected_credentials")[];
            parse_error: components["schemas"]["ErrorCode"] | null;
        };
        SystemConfigRead: {
            state: components["schemas"]["ConfigState"];
            work_path: components["schemas"]["Path"];
            rules_path: components["schemas"]["Path"];
            database_path: components["schemas"]["Path"];
            records_path: components["schemas"]["Path"];
            webui_enabled: boolean;
            webui_address: string;
            webui_port: number;
            public_origin: string | null;
        };
        QueryFilter: {
            from_ms: components["schemas"]["SafeInteger"];
            to_ms: components["schemas"]["SafeInteger"];
            client_id?: components["schemas"]["ClientId"];
            client_ip?: string;
            qname?: string;
            transport?: components["schemas"]["Transport"];
            matched_client_id?: components["schemas"]["ClientId"];
            /** @description 在完整当前目录中解析名称匹配集合，再过滤历史 matched_client_id */
            client_name?: string;
            qtype?: string;
            rcode?: string;
            source?: components["schemas"]["QuerySource"];
            outcome?: components["schemas"]["QueryOutcome"];
            cache?: components["schemas"]["CacheOutcome"];
        };
        QueryRequest: {
            filter: components["schemas"]["QueryFilter"];
            cursor: components["schemas"]["Cursor"] | null;
            /** @enum {string} */
            direction: "older" | "newer";
            /** @default 20 */
            page_size: number;
            /**
             * @description cursor 同时绑定排序和稳定 ID 次序
             * @enum {string}
             */
            sort: "occurred_at" | "duration";
            /** @enum {string} */
            order: "asc" | "desc";
        };
        /** @enum {string} */
        QuerySource: "cache" | "hosts" | "rule" | "upstream" | "synthetic";
        /** @enum {string} */
        QueryOutcome: "answered" | "negative" | "timeout" | "rejected" | "failed";
        /** @enum {string} */
        CacheOutcome: "hit" | "stale" | "miss" | "bypass";
        /** @enum {string} */
        Transport: "udp" | "tcp" | "doh";
        RequestIdentity: {
            client_id: components["schemas"]["ClientId"] | null;
            client_ip: string;
        };
        HistoricalMatch: {
            /** @enum {string} */
            source: "id" | "ip";
            matched_client_id: components["schemas"]["ClientId"];
        } | {
            /** @constant */
            source: "none";
        };
        DnsAnswer: {
            name: string;
            type: string;
            ttl_seconds: number;
            data: string;
        };
        AnswerSummary: {
            /** @enum {string} */
            state: "available" | "truncated";
            records: components["schemas"]["DnsAnswer"][];
            total_count: number;
        } | {
            /** @constant */
            state: "unavailable";
        };
        QueryRecord: {
            id: components["schemas"]["RecordId"];
            occurred_at_ms: components["schemas"]["SafeInteger"];
            identity: components["schemas"]["RequestIdentity"];
            matched: components["schemas"]["HistoricalMatch"];
            current_client_name: components["schemas"]["Name"] | null;
            qname: string;
            qtype: string;
            transport: components["schemas"]["Transport"];
            rcode: string;
            source: components["schemas"]["QuerySource"];
            outcome: components["schemas"]["QueryOutcome"];
            cache: components["schemas"]["CacheOutcome"];
            strategy_name: components["schemas"]["Name"] | null;
            upstream_target_name: components["schemas"]["Name"] | null;
            upstream_used_name: components["schemas"]["Name"] | null;
            cache_producer: components["schemas"]["CacheProducer"] | null;
            duration_us: components["schemas"]["SafeInteger"] | null;
            dns_core_duration_us: components["schemas"]["SafeInteger"] | null;
            answers: components["schemas"]["AnswerSummary"];
        };
        CacheProducer: {
            strategy_name: components["schemas"]["Name"] | null;
            upstream_target_name: components["schemas"]["Name"] | null;
            upstream_used_name: components["schemas"]["Name"] | null;
        };
        CommitCursor: {
            epoch: components["schemas"]["Revision"];
            sequence: components["schemas"]["DecimalU64"];
        };
        QueryPage: {
            items: components["schemas"]["QueryRecord"][];
            previous_cursor: components["schemas"]["Cursor"] | null;
            next_cursor: components["schemas"]["Cursor"] | null;
            snapshot_cursor: components["schemas"]["CommitCursor"];
            directory_revision: components["schemas"]["Revision"];
            retention_revision: components["schemas"]["Revision"];
            available_from_ms: components["schemas"]["SafeInteger"] | null;
        };
        QueryDetail: {
            record: components["schemas"]["QueryRecord"];
            directory_revision: components["schemas"]["Revision"];
        };
        Unavailable: {
            /** @constant */
            state: "unavailable";
            /** @enum {string} */
            reason: "warmup" | "observation_gap" | "sampling_failed" | "unsupported";
        };
        NumberMeasurement: {
            /** @constant */
            state: "available";
            value: number;
        } | components["schemas"]["Unavailable"];
        CountMeasurement: {
            /** @constant */
            state: "available";
            value: number;
        } | components["schemas"]["Unavailable"];
        BytesMeasurement: {
            /** @constant */
            state: "available";
            value: components["schemas"]["DecimalU64"];
        } | components["schemas"]["Unavailable"];
        RateSample: {
            at_ms: components["schemas"]["SafeInteger"];
            value: components["schemas"]["NumberMeasurement"];
        };
        ServiceMetrics: {
            sampled_at_ms: components["schemas"]["SafeInteger"];
            qps: components["schemas"]["NumberMeasurement"];
            rpm: components["schemas"]["NumberMeasurement"];
            online_clients: components["schemas"]["CountMeasurement"];
            rss_bytes: components["schemas"]["BytesMeasurement"];
            qps_trend: components["schemas"]["RateSample"][];
            rpm_trend: components["schemas"]["RateSample"][];
        };
        ProcessMetrics: {
            sampled_at_ms: components["schemas"]["SafeInteger"];
            uptime_seconds: components["schemas"]["SafeInteger"];
            rss_bytes: components["schemas"]["BytesMeasurement"];
            cpu_percent: components["schemas"]["NumberMeasurement"];
            threads: components["schemas"]["CountMeasurement"];
        };
        RetentionStatus: {
            policy: components["schemas"]["Statistics"];
            sampled_at_ms: components["schemas"]["SafeInteger"];
            detail_bytes: components["schemas"]["DecimalU64"];
            /** Format: date */
            cutoff_utc_date: string | null;
            last_completed_at_ms: components["schemas"]["SafeInteger"] | null;
            next_scheduled_at_ms: components["schemas"]["SafeInteger"] | null;
            pending_reclaim_bytes: components["schemas"]["DecimalU64"];
        };
        RetentionPreviewRequest: {
            expected: components["schemas"]["Preconditions"];
            policy: components["schemas"]["Statistics"];
        };
        RetentionPreview: {
            expected: components["schemas"]["Preconditions"];
            sampled_at_ms: components["schemas"]["SafeInteger"];
            detail_bytes: components["schemas"]["DecimalU64"];
            /** Format: date */
            proposed_cutoff_utc_date: string;
            shortens_history: boolean;
        };
        ClientMessage: {
            /** @enum {string} */
            type: "subscribe_metrics" | "unsubscribe";
            subscription_id: components["schemas"]["Revision"];
        } | {
            /** @constant */
            type: "subscribe_queries";
            subscription_id: components["schemas"]["Revision"];
            filter: components["schemas"]["QueryFilter"];
            after: components["schemas"]["CommitCursor"];
        } | {
            /** @constant */
            type: "pong";
            nonce: components["schemas"]["Revision"];
        };
        ServerMessage: {
            /** @constant */
            type: "ready";
            /** @constant */
            protocol_version: 1;
            epoch: components["schemas"]["Revision"];
        } | {
            /** @constant */
            type: "metrics";
            subscription_id: components["schemas"]["Revision"];
            data: components["schemas"]["ServiceMetrics"];
        } | {
            /** @constant */
            type: "queries";
            subscription_id: components["schemas"]["Revision"];
            cursor: components["schemas"]["CommitCursor"];
            directory_revision: components["schemas"]["Revision"];
            items: components["schemas"]["QueryRecord"][];
        } | {
            /** @constant */
            type: "resync_required";
            subscription_id: components["schemas"]["Revision"];
            /** @enum {string} */
            reason: "epoch_changed" | "cursor_expired" | "buffer_overflow" | "observation_gap" | "retention_changed";
        } | {
            /** @constant */
            type: "config_changed";
            active_revision: components["schemas"]["Revision"];
            observed_file_revision: components["schemas"]["Revision"];
        } | {
            /** @constant */
            type: "ping";
            nonce: components["schemas"]["Revision"];
        };
    };
    responses: {
        /** @description 400 形状/参数错误；401 未认证；403 来源/只读字段；404 不存在； 409 revision、operation 或 cursor 冲突；413 超限；422 候选语义不合法； 429 限流；503 owner 不可用。写请求不因 retryable 自动重放。 */
        Error: {
            headers: {
                "X-Request-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSetupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 不披露用户列表的初始化状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    initializeWebUi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description 创建用户并设置 HttpOnly、SameSite=Strict Cookie */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description 建立同源 session；HTTPS 使用 Secure 和 __Host- Cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 撤销 session 及其订阅 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前认证信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getConfigState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前运行和受管双文件状态，不读取外部文件作为活动配置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigState"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSystemConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 启动配置白名单；无用户、hash、私钥或实际 Secret 值 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemConfigRead"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getConfigModule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module: components["schemas"]["ConfigModule"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 有界完整模块集合；values 仅包含请求的模块，不是任意页的局部搜索 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigRead"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    validateCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Candidate"];
            };
        };
        responses: {
            /** @description 绑定候选摘要、影响、active/file revision 的短期 token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            422: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    validateModuleCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module: components["schemas"]["ConfigModule"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Candidate"];
            };
        };
        responses: {
            /** @description 单模块预校验及影响 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    applyModuleCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module: components["schemas"]["ConfigModule"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRequest"];
            };
        };
        responses: {
            /** @description 操作终态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResult"];
                };
            };
            /** @description 操作进行中 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    applyCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRequest"];
            };
        };
        responses: {
            /** @description 已确认操作结果，须检查 status 而不是只检查 HTTP 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResult"];
                };
            };
            /** @description 操作仍在执行 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResult"];
                };
            };
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getConfigOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: components["schemas"]["OperationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 记录过期、重启或未命中返回 unknown，不能据此推断未执行 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getExternalDiff: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 与组合文件观测版本绑定的类型化差异 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalDiff"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    restoreConfigFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileSyncRequest"];
            };
        };
        responses: {
            /** @description 还原结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResult"];
                };
            };
            /** @description 还原进行中 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    retryConfigPersistence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileSyncRequest"];
            };
        };
        responses: {
            /** @description 同步结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResult"];
                };
            };
            /** @description 同步进行中 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    searchQueries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description 捕获 replay 边界后的 HTTP 快照，可与补发重复，按稳定 ID 去重 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryPage"];
                };
            };
            409: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getQueryDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: components["schemas"]["RecordId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 详情及当次目录显示快照；不重算历史 IP 匹配 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRetentionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 共同 UTC 水位和实际物理回收状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetentionStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    previewRetention: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetentionPreviewRequest"];
            };
        };
        responses: {
            /** @description 预览不是删除承诺，实际任务冻结策略并重新采样 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetentionPreview"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getServiceMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description QPS 为近 60 秒请求数/60，RPM 为近 600 秒请求数/10；缺数不能填零 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceMetrics"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProcessMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 与服务指标共享采样口径的进程状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessMetrics"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    subscribeEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebSocket upgrade */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
}
