/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 读取首次初始化状态
         * @description 只返回 required 或 ready，不返回用户名、用户数量或密码 hash。
         */
        get: operations["getSetupStatus"];
        put?: never;
        /**
         * 创建首个管理用户
         * @description 仅在状态为 required 时可调用。服务端先持久化 Argon2id hash，再设置 HttpOnly、 SameSite=Strict Cookie；public_origin 为 HTTPS 时同时设置 Secure 和 __Host- 前缀。
         */
        post: operations["initializeWebUi"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 建立服务端 session
         * @description 成功后由服务端设置 HttpOnly、SameSite=Strict Cookie；public_origin 为 HTTPS 时设置 Secure 和 __Host- 前缀。 服务端校验 Origin 和 Fetch Metadata；前端不持久化 token。
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 终止当前 session
         * @description 服务端必须校验同源 Origin 和 Fetch Metadata，并清除 session Cookie。
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取当前 session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取 Dashboard 摘要 */
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取当前 Runtime 和 bind 摘要 */
        get: operations["getRuntime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取组件健康状态 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取服务端聚合统计 */
        get: operations["getStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 读取解析记录
         * @description 向 authenticated WebUI 用户返回完整 canonical qname、有效 client IP、配置 ID 与有界 answer 摘要；不包含 request digest、route 文本或 DNS wire。历史脱敏记录通过 detail_status=legacy_redacted 显式区分。
         */
        get: operations["getQueries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取资源元数据摘要 */
        get: operations["getResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取系统版本和只读能力 */
        get: operations["getSystem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            code: string;
            message: string;
            request_id: string;
            retryable: boolean;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        /** @enum {string} */
        SetupState: "required" | "ready";
        SetupStatus: {
            state: components["schemas"]["SetupState"];
        };
        SetupRequest: {
            username: string;
            password: string;
        };
        Session: {
            user: components["schemas"]["SessionUser"];
            /** Format: date-time */
            expires_at: string;
        };
        SessionUser: {
            name: string;
        };
        /** @enum {string} */
        HealthStatus: "healthy" | "degraded" | "failed" | "stopping";
        Overview: {
            /** Format: date-time */
            sampled_at: string;
            runtime_revision: string;
            overall_status: components["schemas"]["HealthStatus"];
            cards: components["schemas"]["OverviewCard"][];
            resolution_pipeline: components["schemas"]["ResolutionPipelineStatus"];
        };
        /** @description 进程生命周期内的 DNS 解析完成有界管线计数。cache lookup 状态属于查询完成事件， 异步 cache commit 结果单独计数。 */
        ResolutionPipelineStatus: {
            /**
             * Format: int64
             * @description 被统一 ingress 队列接收的完成事件数量。
             */
            accepted: number;
            /**
             * Format: int64
             * @description 因统一 ingress 队列已满而丢弃的完成事件数量。
             */
            dropped: number;
            /**
             * Format: int64
             * @description 首次 ingress 丢弃的 UTC epoch 毫秒；尚未发生 gap 时为 null。
             */
            gap_started_at_utc_millis: number | null;
            /** Format: int64 */
            cache_commit_stored: number;
            /** Format: int64 */
            cache_commit_rejected: number;
            /** Format: int64 */
            cache_commit_conflict: number;
            /** Format: int64 */
            cache_commit_unavailable: number;
            /**
             * Format: int64
             * @description 在产生 commit 结果前被丢弃的 cache candidate 数量。
             */
            cache_commit_dropped: number;
            /** Format: int64 */
            detail_accepted: number;
            /**
             * Format: int64
             * @description 被有界下游队列丢弃的详情投影数量。
             */
            detail_dropped: number;
            /**
             * Format: int64
             * @description 被 SQLite writer 拒绝的详情投影数量。
             */
            detail_failed: number;
        };
        OverviewCard: {
            /** @enum {string} */
            key: "queries_24h" | "cache_hit_rate" | "failed_queries_24h" | "active_listeners" | "resources";
            label: string;
            value?: number;
            /** @enum {string} */
            unit?: "count" | "percent";
            /** @enum {string} */
            status: "available" | "unavailable";
            unavailable_reason_code?: string;
        };
        /** @enum {string} */
        Transport: "udp" | "tcp" | "doh";
        /** @enum {string} */
        BindState: "active" | "draining";
        RuntimeSnapshot: {
            /** Format: date-time */
            sampled_at: string;
            revision: string;
            /** @description 截断后的非敏感配置摘要，不是原始配置内容 */
            normalized_hash: string;
            listener_count: number;
            bind_count: number;
            resource_count: number;
            has_policy_core: boolean;
            binds: components["schemas"]["BindEntry"][];
        };
        BindEntry: {
            transport: components["schemas"]["Transport"];
            address: string;
            port: number;
            owner: string;
            v6_only: boolean;
            state: components["schemas"]["BindState"];
        };
        HealthSnapshot: {
            /** Format: date-time */
            sampled_at: string;
            overall_status: components["schemas"]["HealthStatus"];
            components: components["schemas"]["ComponentHealth"][];
        };
        ComponentHealth: {
            component: string;
            status: components["schemas"]["HealthStatus"];
            reason_code: string;
            /** Format: date-time */
            first_changed_at?: string | null;
            /** Format: date-time */
            last_changed_at: string;
            /** Format: date-time */
            last_success_at?: string | null;
            retry_count: number;
            stale: boolean;
            gap: boolean;
        };
        /** @enum {string} */
        StatisticDimension: "total" | "transport" | "source" | "rcode" | "outcome" | "cache";
        StatisticsPage: components["schemas"]["PageMeta"] & {
            /** Format: date-time */
            sampled_at: string;
            runtime_revision: string;
            items: components["schemas"]["StatisticItem"][];
        };
        StatisticItem: {
            /** Format: date */
            date: string;
            dimension_kind: components["schemas"]["StatisticDimension"];
            dimension_value: string;
            count: number;
        };
        /** @enum {string} */
        QuerySource: "cache" | "hosts" | "rule" | "upstream" | "synthetic";
        /** @enum {string} */
        Rcode: "NOERROR" | "FORMERR" | "SERVFAIL" | "NXDOMAIN" | "NOTIMP" | "REFUSED" | "OTHER";
        /** @enum {string} */
        QueryOutcome: "answered" | "negative" | "timeout" | "rejected" | "failed";
        /** @enum {string} */
        CacheOutcome: "hit" | "stale" | "miss" | "bypass";
        /** @enum {string} */
        QueryDetailStatus: "available" | "legacy_redacted";
        QueryAnswer: {
            name: string;
            type: string;
            ttl: number;
            data: string;
        };
        QueryPage: components["schemas"]["PageMeta"] & {
            /** Format: date-time */
            sampled_at: string;
            runtime_revision: string;
            items: components["schemas"]["QueryRecord"][];
        };
        QueryRecord: {
            /** @description 不可逆、无业务含义的 opaque ID */
            id: string;
            /** Format: date-time */
            occurred_at: string;
            duration_ms: number;
            transport: components["schemas"]["Transport"];
            source: components["schemas"]["QuerySource"];
            rcode: components["schemas"]["Rcode"];
            outcome: components["schemas"]["QueryOutcome"];
            cache: components["schemas"]["CacheOutcome"];
            policy_matched: boolean;
            resource_matched: boolean;
            detail_status: components["schemas"]["QueryDetailStatus"];
            /** @description canonical ASCII absolute name；历史脱敏记录为 null */
            qname: string | null;
            /** @description 标准 DNS 类型名；未知类型使用 TYPE#### */
            qtype: string;
            /** @description 命中的 clients 配置 ID */
            client_name: string | null;
            /** @description 按 listener/proxy 规则解析后的有效客户端 IPv4/IPv6，不含端口 */
            client_ip: string | null;
            strategy_id: string | null;
            /** @description live 请求的策略目标；cache hit 时为缓存生产请求的目标 */
            upstream_target_id: string | null;
            /** @description 实际产生响应的 direct/member；cache hit 时为缓存生产来源 */
            upstream_used_id: string | null;
            answer_count: number | null;
            answers_truncated: boolean | null;
            answers: components["schemas"]["QueryAnswer"][] | null;
        };
        ResourceSnapshot: {
            /** Format: date-time */
            sampled_at: string;
            runtime_revision: string;
            items: components["schemas"]["ResourceSummary"][];
        };
        ResourceSummary: {
            id: string;
            display_name: string;
            epoch: string;
            revision: string;
            /** @enum {string} */
            source_kind: "const" | "file" | "remote";
            fallback: boolean;
            stale: boolean;
        };
        /** @enum {string} */
        Capability: "read:overview" | "read:runtime" | "read:health" | "read:statistics" | "read:queries" | "read:resources" | "read:system";
        SystemInfo: {
            version: string;
            /** Format: date-time */
            started_at: string;
            uptime_seconds: number;
            capabilities: components["schemas"]["Capability"][];
        };
        PageMeta: {
            page: number;
            page_size: number;
            total_items: number;
        };
    };
    responses: {
        /** @description 参数或同源请求校验失败 */
        BadRequest: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description session 缺失、无效或已过期 */
        Unauthorized: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 当前用户无权读取该资源 */
        Forbidden: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 请求超过管理面限制 */
        RateLimited: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                /** @description 建议重试等待秒数 */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 初始化已完成或源配置发生并发修改 */
        Conflict: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 服务端错误，响应不得包含堆栈或内部路径 */
        InternalError: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description UTC 起始日期，最大查询区间为 31 天 */
        DateFrom: string;
        /** @description UTC 结束日期，包含当天 */
        DateTo: string;
        Dimension: components["schemas"]["StatisticDimension"];
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: {
        /** @description 用于服务端日志关联的非敏感请求标识 */
        RequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSetupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前初始化状态 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    initializeWebUi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description 初始化成功并建立 session */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description session 已终止；重复登出同样成功 */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前 session */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 有界摘要卡片 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getRuntime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前 Runtime 摘要 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeSnapshot"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 健康状态快照 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthSnapshot"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getStatistics: {
        parameters: {
            query: {
                /** @description UTC 起始日期，最大查询区间为 31 天 */
                date_from: components["parameters"]["DateFrom"];
                /** @description UTC 结束日期，包含当天 */
                date_to: components["parameters"]["DateTo"];
                dimension: components["parameters"]["Dimension"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分页聚合结果 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatisticsPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getQueries: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                transport?: components["schemas"]["Transport"];
                source?: components["schemas"]["QuerySource"];
                rcode?: components["schemas"]["Rcode"];
                outcome?: components["schemas"]["QueryOutcome"];
                sort?: "occurred_at" | "duration_ms";
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务端分页的安全投影 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getResources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 资源摘要列表 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceSnapshot"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getSystem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 系统公开摘要 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
}
